add_function_of_election
arafubeatbox/scsportal2 pull request #321
Opened 2022-04-19 18:53 UTC by mugitti9

このPRはポータルに選挙機能をつけることを目的にしたものです。

# 今のサークルにおける選挙の原状
現在SCSにおいては、総会のオンライン化を受け下記のサイトを使って選挙を行っています。
https://tagvote.grinspace.jp
しかしこのサイトではユーザ特定が出来ないため、複数端末を使えば1人複数投票ができる原状があります。また、投票権を持たないはずの立候補者が投票できてしまう可能性があります。
今年になってサークル員全体もそのことを認識しだした＆今後も当分はオンライン or ハイブリット化な総会になることが濃厚であるため、このことが大きな問題として顕在化して来ています。

# 問題点に対する本PRの目的
SCS Portalを用いることで選挙を実装することを目的にしています。
具体的には「選挙作成」「投票」「選挙管理」「開票」がユーザごとに権限が与えられ、実行できるようにしています。
SCS Portalに機能を包含したいと考えた理由としては、SCS PortalはSCSの情報が格納されたDBであるため、複数投票などを明確に防ぐことができると考えたためです。複数投票防止に必要なユーザ認識等は他社サイトであると相応の手間(他社サイトにも登録させるとか？)をかけないと難しいため、Portalに実装することが妥当であると判断しました。
また、SCSにおける諸機能の一元化という目的の延長線上でもあります。

# 本PRの内容
## 下記22個の機能を行えることを最終目標(要件)としています
1. ログイン後のTop画面に選挙の項目が出る
2. ログインしてない場合、選挙関連は一切見れない
3. Electionを作れる
4. Electionの編集画面から選挙を削除できる
5. Election詳細画面で詳細&概要が見れる
6. Electionのhostsは投票できない&編集画面が出て、投票開始前は任意の項目すべてを変更できる
7. Electionのpromotersは投票できない&編集もできない
8. Hostでもpromoterでもない人は、投票期間前は投票ができない
9. ElectionのHostは、投票期間開始後にalternativesを編集できない
10. Hostでもpromoterでもない人は、投票期間中に投票できる
11. Hostでもpromoterでもない人は、投票期間中に投票を変更できる
12. Hostでもpromoterでもない人は、投票期間終了後に投票できない
13. Electionのhostsは、選挙期間終了後に開票ができる
14. 開票の票数があっている
15. Webマスターは昨年度の選挙をまとめて削除できる(またその際に、該当するvote, vote_alternative, election_host, election_promoterがすべて消える)
16. Electionを削除すると該当の選挙のvote_alternativesが消える
17. Electionを削除すると該当の選挙のvoteが全て消える
18. Electionを削除すると該当の選挙のelection_hostsが全て消える
19. Electionを削除すると該当の選挙のelection_promotersが全て消える
20. Userを削除すると該当のユーザのelection_hostsが全て消える
21. Userを削除すると該当のユーザのelection_promotersが全て消える
22. Userを削除すると該当のユーザのvotesが全て消える

## 追加したモデル関連の構成
![Untitled Diagram drawio](https://user-images.githubusercontent.com/33088346/164069634-4994c912-194d-4a36-b007-24fd4a66ab21.png)

上記の様なテーブルを設計した。
Election: 選挙の概要情報を格納
ElectionHost: 選挙のホスト(主催者)情報を格納
ElectionPromoter: 選挙の立候補者情報を格納
VoteAlternative: 投票の選択肢を格納
Vote: 投票情報を格納

またElection, ElectionHost, ElectionPromoterに対しては、必要なDecoratorを作成した

## 追加したコントローラの構成
elections_controller.rb：選挙作成や概要など、選挙自体に関わる部分のコントロール
votes_controller.rb：投票に係る部分のコントロール

## 追加したビューアの構成
### HAMLファイル
#### ①Electionに関するHAML
new.haml：新たに選挙を作成するときに呼び出す(その際に下記2つのファイルを使用)
_election_new_form.haml
/tutorials/_election_new.haml

edit.haml：作成済みの選挙を編集するときに使用(その際に下記1つのファイルを使用)
_election_edit_form.haml

index.haml：作成済み選挙の一覧画面で使用(その際に下記1つのファイルを使用)
_election_table.haml

show.haml：作成済み選挙の詳細画面で使用(その際に下記2つのファイルと_vote_selectを使用)
_election_detail.haml：選挙の概要を表示
_election_result.haml：選挙の結果を表示

last_year_elections_destroy_confirm.html.haml：Webマスターが昨年度の選挙を削除できるようにする画面

#### ②Voteに関するHAML
_vote_select.haml：投票画面を表示

### SCSSファイル
application.scss：election.scssを追加
election.scss：選挙に関する部分のCSS

## 追加したjavascriptのファイル構成
election.js：選挙に関する部分のjsファイル

# 動作画面
概要だけ説明します。
①選挙作成画面
![スクリーンショット2022-04-20（03 36 31）](https://user-images.githubusercontent.com/33088346/164072843-a3ad900d-8b48-422f-9c0b-128bd20873ea.png)
②選挙一覧画面
<img width="1128" alt="スクリーンショット 2022-04-20 3 37 49" src="https://user-images.githubusercontent.com/33088346/164072742-2b0a0e38-c60d-4770-8202-4346db76b1a3.png">
③選挙詳細画面
ここにホストの場合は「開票タブ」、何も権限を持たない場合は「投票タブ」が追加されます。また、ホスト以外にはイベントを編集は表示されません(election/:id/editとURLから打った場合も、ユーザ権限を判断し、権限がない場合は編集画面に遷移させないようにしています)
<img width="1101" alt="スクリーンショット 2022-04-20 3 39 32" src="https://user-images.githubusercontent.com/33088346/164073032-9f2453f8-7937-403b-9363-a8c8ed985e37.png">
<img width="1103" alt="スクリーンショット 2022-04-20 3 40 57" src="https://user-images.githubusercontent.com/33088346/164073265-a039d88e-d6ac-4e3d-a995-74e70cc03eec.png">
④投票画面
投票期間中は下記のように表示されます。
<img width="1100" alt="スクリーンショット 2022-04-20 3 44 08" src="https://user-images.githubusercontent.com/33088346/164073810-d096ff8a-dcdc-40eb-a503-498d11d6f178.png">
また、投票期間中は投票を変更できます。
<img width="1102" alt="スクリーンショット 2022-04-20 3 44 25" src="https://user-images.githubusercontent.com/33088346/164073848-f093c97b-8870-456c-9966-8f450478f317.png">
なお投票期間外は下記のように「投票開始前です」 or 「投票受付終了しました」と表示されます
<img width="1103" alt="スクリーンショット 2022-04-20 3 47 45" src="https://user-images.githubusercontent.com/33088346/164074393-355c61e2-1fcc-4929-b0d2-804d62203ff9.png">
⑤開票画面
投票終了後は下記のように開票されます
<img width="1110" alt="スクリーンショット 2022-04-20 3 48 27" src="https://user-images.githubusercontent.com/33088346/164074493-983c59c0-ee72-4d8b-ab44-7759904ed518.png">
なお投票終了前は下記のように「投票開始前です」 or 「投票期間中です」と表示されます
<img width="1117" alt="スクリーンショット 2022-04-20 3 49 14" src="https://user-images.githubusercontent.com/33088346/164074621-6563d8ed-31d8-47cb-937a-ee1cf69db132.png">
⑥Webマスター昨年度選挙削除画面
昨年度イベント削除と同様の仕様です。
<img width="1112" alt="スクリーンショット 2022-04-20 3 41 35" src="https://user-images.githubusercontent.com/33088346/164073362-cc18ea26-4e1d-4f44-9d8b-7edb62c9953c.png">
<img width="1096" alt="スクリーンショット 2022-04-20 3 41 49" src="https://user-images.githubusercontent.com/33088346/164073406-f9473a9e-8971-4aed-be18-cd5b6e713119.png">

# テストについて
ローカル環境において、上記22個の要件が実行できることを確認済みです。またデプロイいただけた後に、サーバ環境において同様のことが実行できるかどうかを他のサークル員の協力の元でテストする予定です。

2022-04-23 08:04 UTC, arafubeatbox requested changes

2022-04-23 08:04 UTC, arafubeatbox commented on app/models/vote_alternative.rb
> +class VoteAlternative < ApplicationRecord
"Alternative" っていう単語は、ある選択肢が選択されていた場合に存在する「別の選択肢」っていうニュアンスなので、ここではシンプルに "VoteOption" などが良いと思う。

Model、DB、view など変更箇所が多くて、正常に動いているこのブランチで作業するのは心もとないので、このブランチから新しくブランチを切って PR を作成し、base branch をこのブランチにして投げてもらえると助かります。

2022-04-25 12:10 UTC, arafubeatbox requested changes

2022-04-25 12:10 UTC, arafubeatbox commented on app/controllers/votes_controller.rb
> +      redirect_to election_path(@election), notice: "エラーが発生しました。投票し直してください。"
```suggestion
    if @vote.save
      redirect_to election_path(@vote.election), notice: "投票を登録しました"
    else
      redirect_to election_path(@vote.election), notice: "エラーが発生しました。投票し直してください。"
```

2022-04-25 12:10 UTC, arafubeatbox commented on app/controllers/votes_controller.rb
> +      redirect_to election_path(@election), notice: "エラーが発生しました。投票し直してください。"
```suggestion
    if @vote.update(vote_params)
      redirect_to election_path(@vote.election), notice: "投票を変更しました"
    else
      redirect_to election_path(@vote.election), notice: "エラーが発生しました。投票し直してください。"
```

2022-04-26 11:53 UTC, arafubeatbox requested changes

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_detail.haml
> +      -# TODO: Change to code
TODO 不要であれば消しておいて。

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_detail.haml
> +          = hs.full_name
hs: hosts のことかな？細かいけど、ここは promoters なので pm とかに変えておいて。

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_edit_form.haml
> +  });
election_edit_form と election_new_form って何か違いある？
もしない or 少ないなら election_form として切り出して、new/edit.html.erb で使ってほしい。

今のままだと部分テンプレート化している旨味があまりないというか。
ファイルだけ増えている状態に見える。

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_result.haml
> +          = Vote.where(vote_option_id: option.id).count
```suggestion
          = option.votes.count
```

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_result.haml
> +        = Vote.where(election_id: election.id).count
```suggestion
        = option.votes.count
```

ちなみに、view で新たに sql を発行するロジックはなるべく避けたほうがベストかな。
責務は分担すべきで、controller で DB に接続してデータを持ってきて、view はそれを表示するだけにするのがベスト。
vote_option を controller で読み込むときに、include を使ってれば (sql 的には votes が join されるので) 上記変更コードで新たに sql は発行されないはず。

以下は雑談)
本当は includes を使うんじゃなくて、eager_load と preload を使い分けるべきなんだよね。
https://qiita.com/ryosuketter/items/097556841ec8e1b2940f

かなり前に書いたコードで、scsportal2 では view で where してしまっているところあるかもしれない。
そして、preload と eager_load の存在を知らなかったので、includes しか書いてない。
悪い手本のコードとなってしまって申し訳ない。

2022-04-26 11:53 UTC, arafubeatbox commented on app/views/elections/_election_table.haml
> +            -# TODO: 「エントリー受付中」「開催済」「エントリー終了」等ステータスを表示するコードに差替え
TODO 不要であれば消しておいて。

2022-04-28 00:51 UTC, arafubeatbox requested changes

2022-04-28 00:51 UTC, arafubeatbox commented on app/models/election.rb
> +    vote_start <= time && vote_end >= time
お任せするけど、見たところ time に渡されている内容が Time.now しかないので、このメソッド内で Time.now 使って、引数消していいんじゃないかな。

投票受付時間を Time.now 以外で判断する場合も思いつかないし。

2022-04-28 00:51 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +    @elections = Election.includes(:hosts).order("vote_start DESC").order("created_at DESC")
```suggestion
    @elections = Election.includes(:hosts).order(vote_start: :desc, created_at: :desc)
```

2022-04-28 00:51 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +    @vote = @election.votes.where(user_id: current_user.id).blank? ? Vote.new : @election.votes.find_by(user_id: current_user.id)
```suggestion
    @vote = @election.votes.find_by(user_id: current_user.id) || Vote.new
```

2022-04-28 00:51 UTC, arafubeatbox commented on app/views/elections/_election_result.haml
> +        = Vote.where(election_id: election.id).count
そんなんあったんだそういえば！
ありがとう気づかなかった。

2022-04-30 07:37 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +      if params[:election][:options].present?
ここだけわからなかった。
これは vote_option を誤って全削除して更新を押してしまった場合は元々あったもので復元するというロジック？

もしそうだとしたら validation の方が親切だと思われる。

2022-04-30 08:52 UTC, mugitti9 commented on app/controllers/elections_controller.rb
> +      if params[:election][:options].present?
65行目は、選挙期間が始まっているときは、vote_optionを一切更新させたくない(更新してしまうとvote_optionのidが変わってしまい、それに依存するvotesも全部消えてしまうので。それまでの間に投票してしまう人がいるかもしれないので)ということから、
更新かける前のvote_start(選挙期間の最初の日時)によってvote_optionを更新させるかを決めています。
全削除して更新を押してしまった場合は元々あったもので復元する、というよりかは、投票期間中にVoteOptionをいじらせない、という意図です。

if params[:election][:option].present?は、vote_optionが無いときに「undefined method `each' for nil:NilClass」が発生しないようにつけてます(が、validationもかけた方が良いと思ったので、それに関するcommitも追加しておきます！)
(これで回答になってますでしょうか...？)

2022-04-30 12:38 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +      if params[:election][:options].present?
丁寧に説明ありがとう、とりあえず説明はイメージ通りだった。
コメントする位置が悪かったけど、どちらかというと `if params[:election][:options].present?` に対する else の処理に引っ掛かっているんだよね。

>「undefined method `each' for nil:NilClass」が発生しないようにつけてます

これはわかるんだけど、その結果 `@election_options = VoteOption.where(election_id: params[:id])` を実行するモチベーションがわからない。
else 文を取り除いて、nil じゃない場合に option 追加を実行する nil 許容パターンか、nil の時は validation で再度入力を促す nil 禁止パターンかな、と思っていた。

> (が、validationもかけた方が良いと思ったので、それに関するcommitも追加しておきます！)

もしこれで解決するなら問題ない！

2022-04-30 15:13 UTC, mugitti9 commented on app/controllers/elections_controller.rb
> +      if params[:election][:options].present?
なるほど、そちらでしたか、誤解すいません！
@election_optionsをいれないと、render "elections/edit"のタイミングで@election_optionsが無い、という状態になるかな、エラーが発生するかなと誤解して、その部分追加してました。
検討したところいらないだろう、と思ったので修正して(つまり@election_options = VoteOption.where(election_id: params[:id])に該当する部分を消して)、コミットを送りました。お手数おかけして申し訳ありませんがご確認お願いします！

2022-05-03 00:44 UTC, arafubeatbox requested changes

2022-05-03 00:44 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +      end
```suggestion
      params[:election][:options]&.each do |value|
        @election_options << VoteOption.new(name: value, election_id: params[:id]) if value.present?
      end
```

2022-05-03 00:44 UTC, arafubeatbox commented on app/controllers/elections_controller.rb
> +      end
配列が空の場合は each が走らない
配列が nil の場合は safe navigation が動作してくれる

2022-05-03 01:57 UTC, merged